/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boole8Bit_13 (
    input [7:0] a,
    input [7:0] b,
    input [3:0] alufn,
    output reg [7:0] boole
  );
  
  
  
  always @* begin
    
    case (alufn)
      4'h8: begin
        boole[0+7-:8] = a[0+7-:8] & b[0+7-:8];
      end
      4'he: begin
        boole[0+7-:8] = a[0+7-:8] | b[0+7-:8];
      end
      4'h6: begin
        boole[0+7-:8] = a[0+7-:8] ^ b[0+7-:8];
      end
      4'ha: begin
        boole[0+7-:8] = a[0+7-:8];
      end
      4'hc: begin
        boole[0+7-:8] = b[0+7-:8];
      end
      4'h5: begin
        boole[0+7-:8] = ~a[0+7-:8];
      end
      4'h3: begin
        boole[0+7-:8] = ~b[0+7-:8];
      end
      4'h7: begin
        boole[0+7-:8] = ~(a[0+7-:8] & b[0+7-:8]);
      end
      4'h1: begin
        boole[0+7-:8] = ~(a[0+7-:8] | b[0+7-:8]);
      end
      4'h9: begin
        boole[0+7-:8] = ~(a[0+7-:8] ^ b[0+7-:8]);
      end
      default: begin
        boole[0+7-:8] = 8'h00;
      end
    endcase
  end
endmodule
