/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare8Bit_15 (
    input [1:0] alufn,
    input z,
    input v,
    input n,
    output reg [7:0] cmp
  );
  
  
  
  reg lessthan;
  
  reg lessequal;
  
  always @* begin
    lessthan = n ^ v;
    lessequal = z | (n ^ v);
    
    case (alufn)
      2'h1: begin
        cmp = {7'h00, z};
      end
      2'h2: begin
        cmp = {7'h00, lessthan};
      end
      2'h3: begin
        cmp = {7'h00, lessequal};
      end
      default: begin
        cmp = 8'h00;
      end
    endcase
  end
endmodule
